"""file table for bulk upload record

Revision ID: cafe9b6ba540
Revises: 
Create Date: 2026-10-04 14:22:24.858885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cafe9b6ba540'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=False),
    sa.Column('response', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=True),
    sa.Column('status', sa.String(), server_default='initiated', nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hospital_files')
    # ### end Alembic commands ###
